export const nationalityToEmoji = {
  Netherlands: '🇳🇱',
  Mexico: '🇲🇽',
  'United Kingdom': '🇬🇧',
  Monaco: '🇲🇨',
  Spain: '🇪🇸',
  Australia: '🇦🇺',
  Canada: '🇨🇦',
  France: '🇫🇷',
  Thailand: '🇹🇭',
  'United States': '🇺🇸',
  Japan: '🇯🇵',
  Finland: '🇫🇮',
  China: '🇨🇳',
  Denmark: '🇩🇰',
  Germany: '🇩🇪',
  'New Zealand': '🇳🇿',
  Italy: '🇮🇹',
  Brazil: '🇧🇷',
};

export const nationalityToKorean = {
  Netherlands: '네덜란드',
  Mexico: '멕시코',
  'United Kingdom': '영국',
  Monaco: '모나코',
  Spain: '스페인',
  Australia: '호주',
  Canada: '캐나다',
  France: '프랑스',
  Thailand: '태국',
  'United States': '미국',
  Japan: '일본',
  Finland: '핀란드',
  China: '중국',
  Denmark: '덴마크',
  Germany: '독일',
  'New Zealand': '뉴질랜드',
  Italy: '이탈리아',
  Brazil: '브라질',
};
